### ISSUE TITLE
Python argument types did not match C++ signature

### ISSUE THREAD

**Issue by love1323** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#4]
Hello, 
when I run handpose.py met 

Traceback (most recent call last):
  File "handpose.py", line 214, in <module>
    mono_hand_loop(acq, (640,480), config,  track=True, with_renderer=True)
  File "handpose.py", line 113, in mono_hand_loop
    rgbKp = IK.Observations(IK.ObservationType.COLOR, clb, keypoints)
Boost.Python.ArgumentError: Python argument types in
    Observations.__init__(Observations, ObservationType, CameraMeta, numpy.ndarray)
did not match C++ signature:
    __init__(_object*, ObservationType, MBV::Core::CameraMeta, cv::Mat, float, int)
    __init__(_object*, ObservationType, MBV::Core::CameraMeta, cv::Mat)
    __init__(_object*)
    __init__(_object*)

my environment:
python 3.5
numpy 1.16
opencv-python 3.4.3

**Comment by padeler** [comment]
It looks like the issue is on the boost python defined type conversions. Have you imported PyMBVCore in your script?
